# Generated by Django 4.2.3 on 2025-05-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
        ('skill', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='preference.preference'),
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skill.skill'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ending_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='starting_date',
            field=models.DateTimeField(),
        ),
    ]
