# Generated by Django 4.2.3 on 2025-06-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_preferences_event_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
