# Generated by Django 4.2.3 on 2025-03-23 19:31

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, validators=[user.models.validate_rating]),
        ),
    ]
