# Generated by Django 4.2.3 on 2025-06-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rated_by',
            field=models.IntegerField(default=0),
        ),
    ]
