# Generated by Django 4.2.3 on 2025-06-15 20:26

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_rated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0, validators=[user.models.validate_rating]),
        ),
    ]
